#https://www.baeldung.com/spring-boot-h2-database
#TODO: Move to separate yml file with "-h2" to only have this configuration on when the h2 profile is active
spring:
    datasource:
#        url: jdbc:h2:file:~/data/calendar-logbook;AUTO_SERVER=TRUE
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update

#Enable the H2 Console
spring.h2.console.enabled: true
